-- MySQL Script generated by MySQL Workbench
-- Mon May 20 19:32:45 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema voorraad
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema voorraad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `voorraad` DEFAULT CHARACTER SET utf8 ;
USE `voorraad` ;

-- -----------------------------------------------------
-- Table `voorraad`.`Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voorraad`.`Store` (
  `ID` VARCHAR(45) NOT NULL,
  `txt_fullname` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `voorraad`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voorraad`.`Product` (
  `productID` INT NOT NULL,
  `storeID` VARCHAR(45) NOT NULL,
  `txt_name` VARCHAR(45) NULL,
  `int_weight` INT NULL,
  `dat_business` DATE NULL,
  `dat_experation` DATE NULL,
  PRIMARY KEY (`productID`, `storeID`),
  INDEX `StoreID_idx` (`storeID` ASC),
  CONSTRAINT `StoreID`
    FOREIGN KEY (`storeID`)
    REFERENCES `voorraad`.`Store` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `voorraad`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voorraad`.`Login` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `txt_username` VARCHAR(45) NOT NULL,
  `txt_password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `txt_username_UNIQUE` (`txt_username` ASC),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `voorraad`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voorraad`.`User` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `txt_firstname` VARCHAR(45) NULL,
  `txt_lastname` VARCHAR(45) NULL,
  `dat_business` DATE NULL,
  `loginID` INT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `loginID_UNIQUE` (`loginID` ASC),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  CONSTRAINT `LoginId`
    FOREIGN KEY (`loginID`)
    REFERENCES `voorraad`.`Login` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `voorraad`.`UserProduct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voorraad`.`UserProduct` (
  `UserID` INT NOT NULL,
  `ProductID` INT NOT NULL,
  `StoreID` VARCHAR(45) NOT NULL,
  `dat_business` VARCHAR(45) NULL,
  PRIMARY KEY (`UserID`, `ProductID`, `StoreID`),
  INDEX `ProductID_idx` (`ProductID` ASC, `StoreID` ASC),
  CONSTRAINT `UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `voorraad`.`User` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ProductID`
    FOREIGN KEY (`ProductID` , `StoreID`)
    REFERENCES `voorraad`.`Product` (`productID` , `storeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
